William Fei

Nov 5, 2024

In [1]:
import pandas as pd

# Data Cleaning – Sora

In [2]:
sora_full = pd.read_csv("Sora (Porzana carolina), Patuxent River Park, Maryland.csv")

In [3]:
sora_full.columns

Index(['event-id', 'visible', 'timestamp', 'location-long', 'location-lat',
       'motus:batch-id', 'motus:receiver-deployment-id',
       'motus:telemetry-run-id', 'receiver-deployment-id', 'telemetry-run-id',
       'sensor-type', 'individual-taxon-canonical-name',
       'tag-local-identifier', 'individual-local-identifier', 'study-name'],
      dtype='object')

In [4]:
print(str(sora_full['individual-local-identifier'].unique()))

['1412-05676' '1412-05679' '1412-05714' '1412-08765' '1412-05707'
 '1412-08773' '1412-08794' '1412-05698' '1412-05687' '1412-05686'
 '1412-08770' '1412-08788' '1412-05692' '1412-05786' '1412-08736'
 '1412-08760' '1412-08757' '1412-08806' '1412-08822' '1412-08805'
 '1412-08845' '1412-08831' '1412-08825' '1412-08741' '1412-08749'
 '1412-08847' '1412-08791' '1412-08843' '1412-08873' '1412-08842'
 '1412-08849' '1412-08809' '1412-08858' '1412-08878' '1412-08856'
 '1412-08859' '1412-08848' '1412-08844' '1412-08837' '1412-08846'
 '1412-08834' '1412-08808' '1412-08807' '1412-08797' '1412-08911'
 '1412-08912' '1412-08914' '1412-08923' '1412-08869' '1412-08744'
 '1412-08922' '1412-08868' '1412-08933' '1412-58113' '1412-58117'
 '1412-58248' '1412-58122' '1412-58126' '1412-58132' '1412-58135'
 '1412-58137' '1412-58139' '1412-58146' '1412-08951' '1412-58169'
 '1412-58173' '1412-58216' '1412-58190' '1412-08998' '1412-58219'
 '1412-08815' '1412-08816' '1412-58223' '1412-58232' '1412-58120'
 '1412-58245' '1412-58247' '1412-58253' '1412-08910' '1412-08927'
 '1412-08925' '1412-08930' '1412-08932' '1412-58259' '1412-58260'
 '1412-80205' '1412-66788' '1412-77449' '1412-80199' '1412-80213'
 '1412-80214' '1412-66730' '1412-66717' '1412-66762' '1412-66764'
 '1412-66776' '1412-66778' '1412-77414' '1412-66785' '1412-80149'
 '1412-80138' '1412-80161' '1412-80111' '1412-80141' '1412-80113'
 '1412-80139' '1412-80104' '1412-80109' '1412-80215' '1412-77412'
 '1412-80142' '1412-80180' '1412-80212' '1412-77418' '1412-80162'
 '1412-80147' '1412-80140' '1412-80133' '1412-80186' '1412-80158'
 '1412-80218' '1412-77499' '1412-08950' '1412-08952' '1412-08949'
 '1412-58153' '1412-58114' '1412-58170' '1412-08978' '1412-58237'
 '1412-58246' '1412-58258' '1412-80225' '1412-80217' '1412-80208'
 '1412-80216' '1422-07035' '1422-07003' '1412-80300' '1422-07032'
 '1412-80293' '1422-07028' '1412-80291' '1412-80132' '1422-07040'
 '1412-77453' '1412-77442' '1412-77424' '1412-77445' '1412-58291'
 '1422-07036' '1422-07034' '1422-07005' '1412-58172' '1412-77458'
 '1412-80166' '1412-77477' '1412-58166' '1412-58289' '1412-77486'
 '1412-58119' '1412-08956' '1412-58104' '1412-66780' '1412-58125'
 '1412-08919' '1412-08959' '1412-80181' '1412-08955']

Out of the 169 unique Sora ID, I manually went through the plots and decided to keep the following list of 34 sora for visualization:

In [5]:
quality_list = ['1412-05692', '1412-08736', '1412-08744', '1412-08765', '1412-08788', '1412-08797', '1412-08842', '1412-08848', '1412-08858', '1412-08911', '1412-08912', '1412-58113', '1412-58120', '1412-58126', '1412-58169', '1412-58260', '1412-66717', '1412-66762', '1412-66778', '1412-66785', '1412-66788', '1412-80109', '1412-80111', '1412-80205', '1412-80208', '1412-80212', '1412-80213', '1412-80214', '1412-80215', '1412-80216', '1412-80218', '1412-80225', '1422-07028', '1422-07035']

filtered_sora = sora_full[sora_full['individual-local-identifier'].isin(quality_list)]
filtered_sora['individual-local-identifier'].unique()

array(['1412-08765', '1412-08788', '1412-05692', '1412-08736',
       '1412-08842', '1412-08858', '1412-08848', '1412-08797',
       '1412-08911', '1412-08912', '1412-08744', '1412-58113',
       '1412-58126', '1412-58169', '1412-58120', '1412-58260',
       '1412-80205', '1412-66788', '1412-80213', '1412-80214',
       '1412-66717', '1412-66762', '1412-66778', '1412-66785',
       '1412-80111', '1412-80109', '1412-80215', '1412-80212',
       '1412-80218', '1412-80225', '1412-80208', '1412-80216',
       '1422-07035', '1422-07028'], dtype=object)

In [6]:
filtered_sora.head()

,event-id,visible,timestamp,location-long,location-lat,motus:batch-id,motus:receiver-deployment-id,motus:telemetry-run-id,receiver-deployment-id,telemetry-run-id,sensor-type,individual-taxon-canonical-name,tag-local-identifier,individual-local-identifier,study-name
257659,28047214759,True,2018-11-10 23:04:48.000,-76.7113,38.7738,9159740,NaN,NaN,NaN,457677402,radio-transmitter,Porzana carolina,27174.19515,1412-08765,"Sora (Porzana carolina), Patuxent River Park, ..."
257660,28047214760,True,2018-11-10 23:05:01.000,-76.7113,38.7738,9159740,NaN,NaN,NaN,457677402,radio-transmitter,Porzana carolina,27174.19515,1412-08765,"Sora (Porzana carolina), Patuxent River Park, ..."
257661,28047214761,True,2018-11-10 23:05:14.000,-76.7113,38.7738,9159740,NaN,NaN,NaN,457677403,radio-transmitter,Porzana carolina,27174.19515,1412-08765,"Sora (Porzana carolina), Patuxent River Park, ..."
257662,28047214762,True,2018-11-10 23:05:27.000,-76.7113,38.7738,9159740,NaN,NaN,NaN,457677402,radio-transmitter,Porzana carolina,27174.19515,1412-08765,"Sora (Porzana carolina), Patuxent River Park, ..."
257663,28047214763,True,2018-11-10 23:05:39.000,-76.7113,38.7738,9159740,NaN,NaN,NaN,457677404,radio-transmitter,Porzana carolina,27174.19515,1412-08765,"Sora (Porzana carolina), Patuxent River Park, ..."

We will group by 'individual-local-identifier' then filter within each group by first unique location-long. This means dropping duplicates to only keep the first occurrence per bird ID.

In [7]:
def filter_first_unique_location(group):
    return group.drop_duplicates(subset='location-long', keep='first')

filtered_sora_unique_locations = (
    filtered_sora
    .groupby('individual-local-identifier', group_keys=False)
    .apply(filter_first_unique_location)
)[['timestamp', 'location-long', 'location-lat', 'individual-local-identifier']]

In [8]:
filtered_sora_unique_locations.head()

,timestamp,location-long,location-lat,individual-local-identifier
261643,2017-10-17 03:03:05.000,-76.7113,38.7738,1412-05692
264149,2017-10-27 03:53:30.000,-75.9156,36.6718,1412-05692
264153,2017-11-18 05:31:56.000,-81.5922,29.5266,1412-05692
264302,2018-09-12 21:00:06.000,-76.7113,38.7738,1412-08736
274218,2018-11-07 07:01:07.000,-81.2090,31.4895,1412-08736

In [9]:
filtered_sora_unique_locations['timestamp'] = pd.to_datetime(filtered_sora_unique_locations['timestamp'])
filtered_sora_unique_locations['timestamp'] = filtered_sora_unique_locations['timestamp'].apply(lambda x: x.replace(year=2022))
filtered_sora_unique_locations.head()

,timestamp,location-long,location-lat,individual-local-identifier
261643,2022-10-17 03:03:05,-76.7113,38.7738,1412-05692
264149,2022-10-27 03:53:30,-75.9156,36.6718,1412-05692
264153,2022-11-18 05:31:56,-81.5922,29.5266,1412-05692
264302,2022-09-12 21:00:06,-76.7113,38.7738,1412-08736
274218,2022-11-07 07:01:07,-81.2090,31.4895,1412-08736

In [15]:
sora_80214 = filtered_sora_unique_locations[filtered_sora_unique_locations['individual-local-identifier'] == '1412-80214']

In [16]:
sora_80214.head(50)

,timestamp,location-long,location-lat,individual-local-identifier
2438411,2022-05-05 19:16:33,-76.7113,38.7738,1412-80214
2439372,2022-05-21 02:35:56,-77.6258,39.4483,1412-80214
2439412,2022-05-21 03:16:01,-77.9972,39.7104,1412-80214
2439435,2022-05-21 06:46:58,-79.4567,41.8787,1412-80214
2439458,2022-05-21 07:06:13,-79.7017,41.9970,1412-80214
2439490,2022-05-21 07:24:00,-79.6467,42.3087,1412-80214
2439511,2022-05-21 08:26:23,-79.8761,42.9776,1412-80214
2439527,2022-05-23 02:17:27,-80.0120,43.4429,1412-80214
2439535,2022-05-23 02:28:16,-80.0899,43.5089,1412-80214
2439599,2022-05-23 04:27:15,-80.0943,44.0461,1412-80214
2439632,2022-05-23 04:56:40,-80.2237,44.2884,1412-80214
2439732,2022-09-07 05:42:36,-79.5030,44.9404,1412-80214
2439752,2022-09-07 05:48:16,-79.5235,44.9450,1412-80214
2439790,2022-09-07 07:02:28,-79.5501,44.3849,1412-80214
2439861,2022-09-07 07:21:32,-79.4735,44.2803,1412-80214
2439896,2022-10-17 00:13:49,-79.1849,43.8191,1412-80214
2439919,2022-10-17 01:06:40,-78.4040,43.1127,1412-80214
2439970,2022-10-17 04:55:05,-76.9409,40.5274,1412-80214
2439995,2022-10-17 05:03:58,-76.6077,40.4760,1412-80214
2439998,2022-10-17 05:04:37,-76.6825,40.4045,1412-80214
2440016,2022-10-17 05:08:11,-76.7224,40.4263,1412-80214
2440075,2022-10-17 06:54:03,-75.7205,38.8015,1412-80214
2440154,2022-10-17 07:10:52,-76.3845,38.7569,1412-80214
2440237,2022-10-17 08:28:08,-75.8221,37.5887,1412-80214
2440260,2022-10-17 08:48:40,-76.0077,37.3222,1412-80214
2440323,2022-10-17 09:06:46,-76.3551,37.0987,1412-80214
2440355,2022-10-17 09:47:11,-75.9894,36.5270,1412-80214

In [17]:
sora_80214.to_csv('sora_80214.csv', index=False)

In [18]:
sora_80214.to_json()

'{"timestamp":{"2438411":1651778193000,"2439372":1653100556000,"2439412":1653102961000,"2439435":1653115618000,"2439458":1653116773000,"2439490":1653117840000,"2439511":1653121583000,"2439527":1653272247000,"2439535":1653272896000,"2439599":1653280035000,"2439632":1653281800000,"2439732":1662529356000,"2439752":1662529696000,"2439790":1662534148000,"2439861":1662535292000,"2439896":1665965629000,"2439919":1665968800000,"2439970":1665982505000,"2439995":1665983038000,"2439998":1665983077000,"2440016":1665983291000,"2440075":1665989643000,"2440154":1665990652000,"2440237":1665995288000,"2440260":1665996520000,"2440323":1665997606000,"2440355":1666000031000},"location-long":{"2438411":-76.7113,"2439372":-77.6258,"2439412":-77.9972,"2439435":-79.4567,"2439458":-79.7017,"2439490":-79.6467,"2439511":-79.8761,"2439527":-80.012,"2439535":-80.0899,"2439599":-80.0943,"2439632":-80.2237,"2439732":-79.503,"2439752":-79.5235,"2439790":-79.5501,"2439861":-79.4735,"2439896":-79.1849,"2439919":-78.404,"2439970":-76.9409,"2439995":-76.6077,"2439998":-76.6825,"2440016":-76.7224,"2440075":-75.7205,"2440154":-76.3845,"2440237":-75.8221,"2440260":-76.0077,"2440323":-76.3551,"2440355":-75.9894},"location-lat":{"2438411":38.7738,"2439372":39.4483,"2439412":39.7104,"2439435":41.8787,"2439458":41.997,"2439490":42.3087,"2439511":42.9776,"2439527":43.4429,"2439535":43.5089,"2439599":44.0461,"2439632":44.2884,"2439732":44.9404,"2439752":44.945,"2439790":44.3849,"2439861":44.2803,"2439896":43.8191,"2439919":43.1127,"2439970":40.5274,"2439995":40.476,"2439998":40.4045,"2440016":40.4263,"2440075":38.8015,"2440154":38.7569,"2440237":37.5887,"2440260":37.3222,"2440323":37.0987,"2440355":36.527},"individual-local-identifier":{"2438411":"1412-80214","2439372":"1412-80214","2439412":"1412-80214","2439435":"1412-80214","2439458":"1412-80214","2439490":"1412-80214","2439511":"1412-80214","2439527":"1412-80214","2439535":"1412-80214","2439599":"1412-80214","2439632":"1412-80214","2439732":"1412-80214","2439752":"1412-80214","2439790":"1412-80214","2439861":"1412-80214","2439896":"1412-80214","2439919":"1412-80214","2439970":"1412-80214","2439995":"1412-80214","2439998":"1412-80214","2440016":"1412-80214","2440075":"1412-80214","2440154":"1412-80214","2440237":"1412-80214","2440260":"1412-80214","2440323":"1412-80214","2440355":"1412-80214"}}'

In [10]:
# Export the DataFrame to a CSV file named 'sora.csv'
filtered_sora_unique_locations.to_csv('sora.csv', index=False)

# Memory Savings

In [11]:
memory_usage_before_cleaning = sora_full.memory_usage(deep=True).sum() / (1024 ** 3)
memory_usage_after_cleaning = filtered_sora_unique_locations.memory_usage(deep=True).sum() / (1024 ** 3)

In [12]:
print("Memory Usage Before Cleaning:", memory_usage_before_cleaning, "gb")
print("Memory Usage After Cleaning:", memory_usage_after_cleaning, "gb")

Memory Usage Before Cleaning: 4.228238021954894 gb
Memory Usage After Cleaning: 2.065300941467285e-05 gb

The total memory savings of this cleaning script was 99.9991563%.